### ISSUE TITLE
[SUGGESTION] Save Game tab process

### ISSUE THREAD

**Issue by GhostPsi** [saturnsky/saturn_affinity_python#14]
Woud love if the program could permanently keep the game process so you dont have to assign after every reboot. This program is awesome for my 7950x3d and way better than relying on the AMD drivers.

Kind Regards

**Comment by saturnsky** [comment]
@GhostPsi By default, the program is supposed to keep a list of game processes permanently. It creates a save file in the path where the program is located, which can be problematic if the program is running in a path that is not writable.
Can you check if this is the case?

**Comment by GhostPsi** [comment]
> @GhostPsi By default, the program is supposed to keep a list of game processes permanently. It creates a save file in the path where the program is located, which can be problematic if the program is running in a path that is not writable. Can you check if this is the case?

Yupp this was the problem! Thanks for the quick answer and super thanks for the great program!
